# Generated by Django 5.0.7 on 2024-07-24 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
                ('title', models.CharField(default='Unknown', max_length=100, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('publisher', models.CharField(default='Unknown', max_length=100, verbose_name='出版社')),
                ('publication_date', models.DateField(verbose_name='出版日')),
                ('category', models.CharField(default='Unknown', max_length=100, verbose_name='カテゴリー')),
                ('image_link', models.URLField(verbose_name='画像リンク')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('edition', models.IntegerField(verbose_name='版数')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='階数')),
                ('area', models.CharField(max_length=100, verbose_name='エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lend_out', models.BooleanField(default=False, verbose_name='貸出状況')),
                ('reservation_checkout_date', models.DateField(verbose_name='予約貸出日')),
                ('reservation_scheduled_return_date', models.DateField(verbose_name='予約返却予定日')),
                ('checkout_date', models.DateField(verbose_name='貸出日')),
                ('scheduled_return_date', models.DateField(verbose_name='返却予定日')),
                ('return_date', models.DateField(verbose_name='返却日')),
                ('books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='レビュー内容')),
                ('books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.storage'),
        ),
    ]
