# Generated by Django 5.0.7 on 2024-07-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['floor', 'area']},
        ),
    ]
