# Generated by Django 5.0.7 on 2024-07-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(blank=True, null=True, verbose_name='版数'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image_link',
            field=models.URLField(blank=True, null=True, verbose_name='画像リンク'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='出版日'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='books',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='購入日'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
