# Generated by Django 5.0.7 on 2024-07-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_books_author_alter_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=100, verbose_name='ISBN'),
        ),
    ]
