# Generated by Django 5.0.7 on 2024-07-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_books_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='books_id',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='lending',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='books_id',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
