# Generated by Django 5.0.7 on 2024-07-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_books_id_lending_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='is_lend_out',
        ),
        migrations.AddField(
            model_name='books',
            name='is_lend_out',
            field=models.BooleanField(default=False, verbose_name='貸出状況'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='checkout_date',
            field=models.DateField(null=True, verbose_name='貸出日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='reservation_checkout_date',
            field=models.DateField(null=True, verbose_name='予約貸出日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='reservation_scheduled_return_date',
            field=models.DateField(null=True, verbose_name='予約返却予定日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='return_date',
            field=models.DateField(null=True, verbose_name='返却日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='scheduled_return_date',
            field=models.DateField(null=True, verbose_name='返却予定日'),
        ),
    ]
