# Generated by Django 5.0.7 on 2024-07-26 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_lending_is_lend_out_books_is_lend_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.storage', verbose_name='保管場所'),
        ),
    ]
