# Generated by Django 5.0.7 on 2024-07-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_books_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_lend_out',
            field=models.BooleanField(blank=True, default=False, verbose_name='貸出状況'),
        ),
    ]
