# Generated by Django 5.0.7 on 2024-07-29 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_books_is_lend_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.storage', verbose_name='保管場所'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='area',
            field=models.CharField(max_length=100, null=True, verbose_name='エリア'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='階数'),
        ),
    ]
