# Generated by Django 5.0.7 on 2024-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_books_storage_alter_storage_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='貸出日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='reservation_checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='予約貸出日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='reservation_scheduled_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='予約返却予定日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='返却日'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='scheduled_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='返却予定日'),
        ),
    ]
