# Generated by Django 5.0.7 on 2024-07-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_lending_checkout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_lend_out',
            field=models.BooleanField(default=False, verbose_name='貸出状況'),
        ),
    ]
