# Generated by Django 5.0.7 on 2024-08-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_books_is_lend_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='return_date',
            field=models.DateField(null=True, verbose_name='返却日'),
        ),
    ]
