# Generated by Django 5.0.7 on 2024-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_lending_cancel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='cancel_date',
            field=models.DateField(blank=True, null=True, verbose_name='予約キャンセル日'),
        ),
        migrations.AddField(
            model_name='lending',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='返却日'),
        ),
    ]
