# Generated by Django 5.0.7 on 2024-08-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_books_storage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('floor', 'area'), name='unique_floor_area'),
        ),
    ]
