# Generated by Django 5.0.7 on 2024-09-11 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='ISBNは「97」で始まる13桁の数字である必要があります。', regex='^97\\d{11}$')], verbose_name='ISBN'),
        ),
    ]
